// Code generated by Kitex v0.9.1. DO NOT EDIT.
package konataservice

import (
	server "github.com/cloudwego/kitex/server"
	konata_client "github.com/hhr12138/Konata-client/kitex_gen/db/raft/konata_client"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler konata_client.KonataService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler konata_client.KonataService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
